### ISSUE TITLE
User problems

### ISSUE THREAD

**Issue by Mohammed-App-creater** [teta-so/cms-dart#8]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Mohammed-App-creater** [comment]
There is a problem in user setting it doesn't allow me to to write and safe any thing

**Comment by Stratofighter** [comment]
I try to upload a 1024x1024 png image for my icon but no matter what I do, it just won't work. I have 10 times checked for transparancy and have exported my image in every variable configuration of PNG I possibly can. It just won't work. I am super frustrated.
